name = "KeywordCalls"
uuid = "4d827475-d3e4-43d6-abe3-9688362ede9f"
authors = ["Chad Scherrer <chad.scherrer@gmail.com> and contributors"]
version = "0.1.1"

[deps]
GeneralizedGenerated = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
NestedTuples = "a734d2a7-8d68-409b-9419-626914d4061d"

[compat]
julia = "1"
GeneralizedGenerated = "0.3"
MLStyle = "0.4"
NestedTuples = "0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
